# Arrays

* Array is a collection of similar data elements,each identified by at least one array index and this elements are stored at contiguous memory locations.

* size of an array is fixed.

# Creating an array in python

In [1]:
from array import *
arr1 = array("i",[4,7,2,9,8])
arr2 = array("d",[9.8,7.5,5.9,8.1])
print(arr1)
print(arr2)

array('i', [4, 7, 2, 9, 8])
array('d', [9.8, 7.5, 5.9, 8.1])


* Time complexity : O(1)

# Insertion

In [2]:
from array import *
arr1 = array("i",[4,7,2,9,8])
print(arr1)
arr1.insert(5,90)
print(arr1)

array('i', [4, 7, 2, 9, 8])
array('i', [4, 7, 2, 9, 8, 90])


# Insert element at beginning

In [4]:
from array import *
arr1 = array("i",[4,7,2,9,8])
print(arr1)
arr1.insert(0,0)
print(arr1)

array('i', [4, 7, 2, 9, 8])
array('i', [0, 4, 7, 2, 9, 8])


# Array traversal

In [5]:
from array import *
arr1 = array("i",[4,7,2,9,8])
def traverse(array):
    for i in array:
        print(i,end=" ")
traverse(arr1)

4 7 2 9 8 

* Time complexity : O(n)

# Access array element

In [8]:
from array import *
arr1 = array("i",[4,7,2,9,8])
def access(array,index):
    if index >= len(array):
        print("Array is full")
    else:
        print(array[index])
access(arr1,4)

8


# Finding an element

In [12]:
from array import *
arr1 = array("i",[4,7,2,9,8])
def searchinArray(array,value):
    for i in array:
        if i == value:
            return array.index(value)
    
    return "Key is not in the array"
print(searchinArray(arr1,8))

4


# Deletion

In [13]:
from array import *
arr1 = array("i",[4,7,2,9,8])
arr1.remove(7)
print(arr1)

array('i', [4, 2, 9, 8])


# One dimensional array - practice

In [28]:
from array import *
#create an array and traverse
my_array = array('i',[1,8,9,7,6,4])
for i in my_array:
    print(i,end=" ")
#Access  Individual elements through indexes
print()
print("first element -",my_array[0])

#Append any value to any array using append method
my_array.append(11)
print("After appending -",my_array)

#insert value to an array using insert method.
my_array.insert(1,5)
print("After inserting -",my_array)

#Extend python array using extend method.
my_array1 = array('i',[99,77,66,55,22])
my_array.extend(my_array1)
print("After extending -",my_array)

#Add items from list into array using fromist() method
tempList =[65,89,34,21,54]
my_array.fromlist(tempList)
print("After fromlist()-",my_array)

#remove any array element using remove method.
my_array.remove(1)
print("after remove -",my_array)

#Removing last method using pop() method.
my_array.pop()
print("After popping -",my_array)

#Fetch any element in an array using index() method.
print("index of 66 -",my_array.index(66))

#Reverse an python array using reverse mthod.
my_array.reverse()
print("After reversing array -",my_array)

#Get array buffer information through buffer_info() method.
print("buffer information")
print(my_array.buffer_info())

#check the number of occurrence of an element in an array using count method.
print("count of 9 -",my_array.count(99))

#Convert array to string using tostring() method.
stringTemp = my_array.tostring()
print("after converting array to string -",stringTemp)
ints = array('i')
ints.fromstring(stringTemp)
print("after converting array to string -",ints)

#Convert array to list using tolist() method.
#print("converting to list -",my_array.tolist())

#Slice elements from an array.
print("After slicing -",my_array[1:4])

1 8 9 7 6 4 
first element - 1
After appending - array('i', [1, 8, 9, 7, 6, 4, 11])
After inserting - array('i', [1, 5, 8, 9, 7, 6, 4, 11])
After extending - array('i', [1, 5, 8, 9, 7, 6, 4, 11, 99, 77, 66, 55, 22])
After fromlist()- array('i', [1, 5, 8, 9, 7, 6, 4, 11, 99, 77, 66, 55, 22, 65, 89, 34, 21, 54])
after remove - array('i', [5, 8, 9, 7, 6, 4, 11, 99, 77, 66, 55, 22, 65, 89, 34, 21, 54])
After popping - array('i', [5, 8, 9, 7, 6, 4, 11, 99, 77, 66, 55, 22, 65, 89, 34, 21])
index of 66 - 9
After reversing array - array('i', [21, 34, 89, 65, 22, 55, 66, 77, 99, 11, 4, 6, 7, 9, 8, 5])
buffer information
(570979316880, 16)
count of 9 - 1
after converting array to string - b'\x15\x00\x00\x00"\x00\x00\x00Y\x00\x00\x00A\x00\x00\x00\x16\x00\x00\x007\x00\x00\x00B\x00\x00\x00M\x00\x00\x00c\x00\x00\x00\x0b\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x05\x00\x00\x00'
after converting array to string - array('i', [21, 34, 89, 65, 22, 55, 66, 

# Two dimensional array

In [29]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# insertion - two dimensional array

In [41]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)
#Adding column in two dimensional array
newtwoDArray = np.insert(twoDArray, 0,[[77,99,22]], axis=1)
print(newtwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  1  2  3  4]
 [99  5  6  7  8]
 [22  9 10 11 12]]


In [43]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)
#Adding row in two dimensional array
newtwoDArray = np.insert(twoDArray, 1,[[0,0,0,0]], axis=0)
print(newtwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)
#Adding a row
newtwoDArray = np.append(twoDArray,[[90,50,100,299]],axis=0)
print(newtwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 90  50 100 299]]


In [50]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)
#Adding column to 2 dimensional array
newtwoDArray = np.append(twoDArray,[[90],[50],[100]],axis=1)
print(newtwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   2   3   4  90]
 [  5   6   7   8  50]
 [  9  10  11  12 100]]


# Access an element of 2 dimensional array

In [51]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

def accessElement(array,rowIndex,colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print("Incorrect index")
    else:
        print(array[rowIndex][colIndex])
accessElement(twoDArray,1,1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6


# Traversal

In [52]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

def traverseArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j],end=" ")
traverseArray(twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

In [71]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

def searchArray(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return "Element is found at"+" "+"row"+" "+ str(i)+" "+"column"+" "+str(j)
    return "Element not found"                 
print(searchArray(twoDArray,7))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element is found at row 1 column 2


# Deletion-Two Dimensional Array

In [4]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

#deleting first column
newTwoDArray = np.delete(twoDArray,0,axis=1)
print()
print(newTwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [3]:
import numpy as np
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twoDArray)

#deleting first row
newTwoDArray = np.delete(twoDArray,0,axis=0)
print()
print(newTwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 5  6  7  8]
 [ 9 10 11 12]]


# When to use arrays

* To store multiple variables of same data type
* Random Access

# When to avoid arrays

* Reserve memory
* Same data type elements